### ISSUE TITLE
deprecation warning for NPNProtocols

### ISSUE THREAD

**Issue by spierenburg** [robertklep/nefit-easy-core#13]
hi Robert, I really love your work. I noticed there is a deprecation warning for tls.convertNPNProtocols() since nodejs 10.0. Is there an easy fix for this?

**Comment by robertklep** [comment]
Thanks for the warning!

It's probably caused by a dependency, I'll check and see if there's an update available.

**Comment by robertklep** [comment]
`nefit-easy-core@2.0.1` released which fixes this (and some other) deprecation warning.

I'll update dependent packages as well.

**Comment by spierenburg** [comment]
thanks!
