### ISSUE TITLE
fix for node 4?

### ISSUE THREAD

**Issue by sweebee** [robertklep/nefit-easy-core#15]
The plugin stopped working because something changed at the endpoint I guess, but I'm using node 4 and nefit-easy-commands, is there a way to get it working with node 4 again?

**Comment by robertklep** [comment]
The changes that were required to get everything up and running again included having to use an entirely different XMPP client, which has a hard dependency of Node 6 or higher.

It _might_ be possible to use Babel to transpile the module to a version of JS that Node 4 can understand, but perhaps it's just easier to bite the bullit and upgrade your Node (which typically isn't very difficult; most Linux distributions provide outdated/deprecated Node versions in their default repositories, but there are lots of alternative repositories that provide recent Node versions: https://nodejs.org/en/download/package-manager/).

**Comment by sweebee** [comment]
I'm using https://github.com/sweebee/pimatic-nefit/ with pimatic, but pimatic doesn't work yet on higher node versions.

will try babel

**Comment by robertklep** [comment]
Due to other issues, I reverted back to the previous XMPP client, which also brought back Node v4 support (as of `nefit-easy-core@4.0.0`, `nefit-easy-commands@3.0.2` and `nefit-easy-http-server@5.0.2`).
