### ISSUE TITLE
Difference due to used m3 value calculations

### ISSUE THREAD

**Issue by jaapdevries** [robertklep/nefit-easy-core#17]
The comments say:

> Value is in kWh.
> To convert to m³, the Easy uses a conversion factor of 0.12307692F (kWh * 0.12307692f = m³) for natural gas (which means a calorific value of 29MJ/m³).

First the Easy does not convert to m3, only kWh values are used, so perhaps "the Easy uses a conversion factor" should be changed . Apart from that using the proposed calculation I've noticed a huge difference in measured m3 vs actual m3 usage (slimme meter and monthly overview).

For example:
**November 2018**
Nefit Easy: 1631.6 kWh
Mentioned calculation: 1631.6 * 0.12307692 = 200.812302672 m3
Actual m3 usage (Essent, Limburg) = 154 m3

Using data from [https://www.gasunietransportservices.nl/aangeslotenen/gaskwaliteit-en-meetzaken/calorische-waarden](https://www.gasunietransportservices.nl/aangeslotenen/gaskwaliteit-en-meetzaken/calorische-waarden) and other websites the calculation perhaps should be:

1 kWh = 3.6 MJ
1 m3 = 35.059900 MJ *

_* not yet sure what stationcode I need to use but this seems to be the most common value_

**November 2018 with altered calculation**
Nefit Easy: 1631.6 kWh
Proposed calculation: (1631.6 * 3.6) / 35.059900 = 167.534990117 m3
Actual m3 usage (Essent, Limburg) = 154 m3

A difference in m3 is also noticeable, but using this calculation my year estimate is off by 22 m3 instead of 250 m3. And if you are using the data from the Nefit Easy to monitor gas usage this is a rather big difference.

**Comment by jaapdevries** [comment]
https://unit-converter.gasunie.nl/ also uses mentioned calculation for conversion from kwh to m3

**Comment by robertklep** [comment]
I meant to say _"the Easy **app** uses a conversion factor of..."_. I'll fix that, and include a link to the Gasunie site for Dutch customers to look up a more specific calorific value.
