### ISSUE TITLE
Handle (potential) TLS errors when running in server mode

### ISSUE THREAD

**Issue by robertklep** [robertklep/nefit-easy-core#2]
https://www.domoticz.com/forum/viewtopic.php?p=68553#p68553

Handle both `client.connection.socket.on('error', ...)` and `client.on('error', ...)` (move latter to top-level of lib, assume that any errors are unrecoverable and require reconnect). Use [`reconnect-core`](https://github.com/juliangruber/reconnect-core)?

**Comment by pepijng** [comment]
Testing it right now
